# version: "3.9"  # Removed obsolete version

services:
  db:
    image: postgres:16-alpine
    container_name: food_dataset_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: food_dataset
      POSTGRES_USER: kelvin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d food_dataset"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food_dataset_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://kelvin:admin@db:5432/food_dataset?schema=public
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"   # ðŸ‘ˆ required for server nginx
    command: sh -c "npx prisma migrate deploy && npm run start"

volumes:
  postgres_data:
